### ISSUE TITLE
Repo organisation

### ISSUE THREAD

**Issue by JulienPeloton** [JulienPeloton/spark3D#14]
The spark3D is organized the following

![organisation](https://user-images.githubusercontent.com/20426972/40344975-804f7e78-5d97-11e8-8a3f-df5b0406ead5.jpg)

that is from the user point of view, spark3D provides 2 main services:
* creating a Shape3D RDD (Point3D, Sphere) from a raw RDD. The Shape3D RDD are RDD whose elements are Shape3D. They have the same partitioning as the raw RDD.
* re-partition a Shape3D RDD, based on implemented partitioners. Partitioned Shape3D RDD are RDD whose elements are Shape3D, plus a specific partitioning.

**Comment by ChristianArnault** [comment]
Add a I/O module to connect to Spark-Fits or CSV

**Comment by ChristianArnault** [comment]
Long term:
- query API

**Comment by JulienPeloton** [comment]
> Add a I/O module to connect to Spark-Fits or CSV

Done for Point3DRDD! See [here](https://github.com/JulienPeloton/spark3D/blob/master/src/main/scala/com/spark3d/spatial3DRDD/Point3DRDD.scala).
